<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="behaviourstates"
    nsURI="http://ecno.se.imm.dtu.dk/ecno/save/bahaviourstates" nsPrefix="behaviourstates">
  <eClassifiers xsi:type="ecore:EClass" name="BehaviourStates">
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="#//ElementBehaviourState" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orphans" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="added" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controllerConfig" eType="#//ControllerConfigurator"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packages" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BehaviourState" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="DefaultState" eSuperTypes="#//BehaviourState"/>
  <eClassifiers xsi:type="ecore:EClass" name="PTNetState" eSuperTypes="#//BehaviourState">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="marking" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InheritedBehaviourState" eSuperTypes="#//BehaviourState">
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="#//BehaviourState" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefaultContainer" eSuperTypes="#//BehaviourState"/>
  <eClassifiers xsi:type="ecore:EClass" name="ElementBehaviourState">
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" lowerBound="1" eType="#//BehaviourState"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControllerConfigurator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" eType="#//ControllerState"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControllerState" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectReference" eSuperTypes="#//ControllerState">
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
</ecore:EPackage>
