/**
 * This is an automatically generated class. It was generated by the
 * ECNO framework. It defines an Event_Value class.
 */
package dk.dtu.imm.se.ecno.examples.workers.events;

import java.util.Collection;
import java.util.Collections;
import java.util.List;

import dk.dtu.imm.se.ecno.core.IEventType;
import dk.dtu.imm.se.ecno.core.IFormalParameter;
import dk.dtu.imm.se.ecno.runtime.Event; 
import dk.dtu.imm.se.ecno.runtime.Event_Values;

public class DoJob extends Event_Values  {

	final public dk.dtu.imm.se.ecno.examples.workers.Job job;
	final public Collection<dk.dtu.imm.se.ecno.examples.workers.Worker> workers;
	final public java.lang.String newName;

	@SuppressWarnings("unchecked")
	public DoJob(IEventType type, Event event) {
		super(type.getDirectSuperType(), event);
		List<IFormalParameter> formalParameters = type.getFormalParametersList();           	
	    job = (dk.dtu.imm.se.ecno.examples.workers.Job) event.getParameter(formalParameters.get(0)).getValue();
	    workers = Collections.unmodifiableCollection((Collection<dk.dtu.imm.se.ecno.examples.workers.Worker>) event.getParameter(formalParameters.get(1)).getValue());
	    newName = (java.lang.String) event.getParameter(formalParameters.get(2)).getValue();
	}
}
