/**
 * This is an automatically generated class. It was generated by the
 * Petri net component of the ECNO framework. This class defines
 * the behaviour of an element, as defined by the Petri net.
 */
package example.ecno.vendingmachine.automata;

import org.eclipse.emf.ecore.EObject;

import dk.dtu.imm.se.ecno.model.runtime.ecnonets.AbstractPetrinetBehaviour;
import dk.dtu.imm.se.ecno.model.runtime.ecnonets.PetriNetChoice;
import dk.dtu.imm.se.ecno.runtime.ParentAction;
import dk.dtu.imm.se.ecno.core.IElementType;
import dk.dtu.imm.se.ecno.core.IPackageAdapter;
import dk.dtu.imm.se.ecno.engine.ExecutionEngine; 

@SuppressWarnings("unused")
public class Slot extends AbstractPetrinetBehaviour<example.emf.vendingmachine.Slot> {
	
	public Slot(ExecutionEngine engine, IElementType type,  EObject element) {
		super(engine, (example.emf.vendingmachine.Slot) element, new int[]{}, new String[]{"t13", "t14", "t15"}, type );
	}
	
	@Override
	public boolean enabled(int t) {
		switch (t) {
		case 0:
			return true;
                    
		case 1:
			return true;
                    
		case 2:
			return true;
                    
		default:
			return false;	
		}
	}
	
	@Override
	public void consumeTokens(int t, int[] m) {
		switch (t) {
		case 0:
            break;
                    
		case 1:
            break;
                    
		case 2:
            break;
                    
		}
	}

	@Override
	public boolean dropParentChoice(int t) {
		switch (t) {
		case 0:
			return false;                    
		case 1:
			return false;                    
		case 2:
			return false;                    
		default:
			return false;	
		}
	}

	@Override
	public void fireImpl(int t) {
		if (! enabled(t))
			return;
		
		switch (t) {
		case 0:		
			break;
			
		case 1:		
			break;
			
		case 2:		
			break;
						
		}
	}
	
	@Override
	public String[] getTransitionEventParameterNames(int transition, int event) {
		switch (transition) {
		case 0:
			switch (event) {
			case 0:
				return new String[] { "slot" };
            default: return new String[] {};
                }
		case 1:
			switch (event) {
			case 0:
				return new String[] { "slot" };
            default: return new String[] {};
                }
		case 2:
			switch (event) {
			case 0:
				return new String[] {};
			case 1:
				return new String[] { "slot" };
            default: return new String[] {};
                }
		default: return new String[] {};
		}  
	}	
	
	@Override
	public Object getParamAssignment(PetriNetChoice choice, int event, int param) {
		int transition = choice.getTransition();
		// Note that this attribute self will be deleted in future versions 
		// of the ECNO code generator for ECNO nets. Therefore, the method
		// self() should be used instead of the variable self in your 
		// ECNO Net Java code snippets.
		example.emf.vendingmachine.Slot self = self();
				
		switch (transition) {
		case 0: {
			example.ecno.vendingmachine.events.Pass p = 
			    (example.ecno.vendingmachine.events.Pass) choice.getEventValues("pass");
			switch (event) {
			case 0:
				switch (param) {      
				case 0: return self();			    
                default: return null;
                }
			default: return null;
			}
		}
		case 1: {
			example.ecno.vendingmachine.events.Insert i = 
			    (example.ecno.vendingmachine.events.Insert) choice.getEventValues("insert");
			switch (event) {
			case 0:
				switch (param) {      
				case 0: return self();			    
                default: return null;
                }
			default: return null;
			}
		}
		case 2: {
			example.ecno.vendingmachine.events.Return_ r = 
			    (example.ecno.vendingmachine.events.Return_) choice.getEventValues("return_");
			switch (event) {
			case 0:
				switch (param) {    
                default: return null;
                }
			case 1:
				switch (param) {      
				case 0: return self();			    
                default: return null;
                }
			default: return null;
			}
		}
		default: return null;
		}  
	}	

	@Override
	public boolean evaluateCondition(PetriNetChoice choice) {
		int transition = choice.getTransition();
		// Note that this attribute self will be deleted in future versions 
		// of the ECNO code generator for ECNO nets. Therefore, the method
		// self() should be used instead of the variable self in your 
		// ECNO Net Java code snippets.
		example.emf.vendingmachine.Slot self = self();
		
		switch (transition) {
		case 0: {
			example.ecno.vendingmachine.events.Pass p = 
                (example.ecno.vendingmachine.events.Pass) choice.getEventValues("pass");
			return true; 
		}
		case 1: {
			example.ecno.vendingmachine.events.Insert i = 
                (example.ecno.vendingmachine.events.Insert) choice.getEventValues("insert");
			return self().getCoin().size() < 2; 
		}
		case 2: {
			example.ecno.vendingmachine.events.Return_ r = 
                (example.ecno.vendingmachine.events.Return_) choice.getEventValues("return_");
			return true; 
		}
		default: return false;
		}  
	}	
	
	@Override
	public void executeAction(PetriNetChoice choice) {
		int transition = choice.getTransition();
		ParentAction parent = new ParentAction(choice);
		// Note that this attribute self will be deleted in future versions 
		// of the ECNO code generator for ECNO nets. Therefore, the method
		// self() should be used instead of the variable self in your 
		// ECNO Net Java code snippets.
		example.emf.vendingmachine.Slot self = self();
		
		switch (transition) {
		case 0: {
			example.ecno.vendingmachine.events.Pass p =
                (example.ecno.vendingmachine.events.Pass) choice.getEventValues("pass");
{
self().getCoin().remove(p.coin);
}
            fire(transition);
			return; 
		}
		case 1: {
			example.ecno.vendingmachine.events.Insert i =
                (example.ecno.vendingmachine.events.Insert) choice.getEventValues("insert");
{
self().getCoin().add(i.coin);
}
            fire(transition);
			return; 
		}
		case 2: {
			example.ecno.vendingmachine.events.Return_ r =
                (example.ecno.vendingmachine.events.Return_) choice.getEventValues("return_");
{
self().getCoin().clear();
}
            fire(transition);
			return; 
		}
		default: return;
		}  
	}	
	
	@Override
	public String[] getTransitionEvents(int transition) {
			switch (transition) {
		case 0: 
			return new String[] { "pass" };
		case 1: 
			return new String[] { "insert" };
		case 2: 
			return new String[] { "reset", "return_" };
		default: return null;
		}  
	}
		
}

