/**
 * This is an automatically generated class. It was generated by the
 * ECNO framework. It defines an Event_Value class.
 */
package dk.dtu.compute.se.ecno.processalgebras.events;

import java.util.List;

import dk.dtu.imm.se.ecno.core.IEventType;
import dk.dtu.imm.se.ecno.core.IFormalParameter;
import dk.dtu.imm.se.ecno.runtime.Event; 
import dk.dtu.imm.se.ecno.runtime.Event_Values;

public class CheckProcess extends Event_Values  {

	final public dk.dtu.compute.se.emf.processalgebra.ProcessInstance process;

	public CheckProcess(IEventType type, Event event) {
		super(type.getDirectSuperType(), event);
		List<IFormalParameter> formalParameters = type.getFormalParametersList();           	
	    process = (dk.dtu.compute.se.emf.processalgebra.ProcessInstance) event.getParameter(formalParameters.get(0)).getValue();
	}
}
