/**
 * This is an automatically generated class. It was generated by the
 * Petri net component of the ECNO framework. This class defines
 * the behaviour of an element, as defined by the Petri net.
 */
package ecno.bankingsystem.localbehaviour;

import org.eclipse.emf.ecore.EObject;

import dk.dtu.imm.se.ecno.model.runtime.ecnonets.AbstractPetrinetBehaviour;
import dk.dtu.imm.se.ecno.model.runtime.ecnonets.PetriNetChoice;
import dk.dtu.imm.se.ecno.runtime.ParentAction;
import dk.dtu.imm.se.ecno.core.IElementType;
import dk.dtu.imm.se.ecno.core.IPackageAdapter;
import dk.dtu.imm.se.ecno.engine.ExecutionEngine; 

@SuppressWarnings("unused")
public class Account extends AbstractPetrinetBehaviour<emf.bankingsystem.Account> {
	
	public Account(ExecutionEngine engine, IElementType type,  EObject element) {
		super(engine, (emf.bankingsystem.Account) element, new int[]{}, new String[]{"t27", "t45", "t46", "t55"}, type );
	}
	
	@Override
	public boolean enabled(int t) {
		switch (t) {
		case 0:
			return true;
                    
		case 1:
			return true;
                    
		case 2:
			return true;
                    
		case 3:
			return true;
                    
		default:
			return false;	
		}
	}
	
	@Override
	public void consumeTokens(int t, int[] m) {
		switch (t) {
		case 0:
            break;
                    
		case 1:
            break;
                    
		case 2:
            break;
                    
		case 3:
            break;
                    
		}
	}

	@Override
	public boolean dropParentChoice(int t) {
		switch (t) {
		case 0:
			return false;                    
		case 1:
			return false;                    
		case 2:
			return false;                    
		case 3:
			return false;                    
		default:
			return false;	
		}
	}

	@Override
	public void fireImpl(int t) {
		if (! enabled(t))
			return;
		
		switch (t) {
		case 0:		
			break;
			
		case 1:		
			break;
			
		case 2:		
			break;
			
		case 3:		
			break;
						
		}
	}
	
	@Override
	public String[] getTransitionEventParameterNames(int transition, int event) {
		switch (transition) {
		case 0:
			switch (event) {
			case 0:
				return new String[] { "account" };
            default: return new String[] {};
                }
		case 1:
			switch (event) {
			case 0:
				return new String[] {  };
            default: return new String[] {};
                }
		case 2:
			switch (event) {
			case 0:
				return new String[] {  };
            default: return new String[] {};
                }
		case 3:
			switch (event) {
			case 0:
				return new String[] { "balance" };
            default: return new String[] {};
                }
		default: return new String[] {};
		}  
	}	
	
	@Override
	public Object getParamAssignment(PetriNetChoice choice, int event, int param) {
		int transition = choice.getTransition();
		// Note that this attribute self will be deleted in future versions 
		// of the ECNO code generator for ECNO nets. Therefore, the method
		// self() should be used instead of the variable self in your 
		// ECNO Net Java code snippets.
		emf.bankingsystem.Account self = self();
				
		switch (transition) {
		case 0: {
			ecno.bankingsystem.events.CreateSession c = 
			    (ecno.bankingsystem.events.CreateSession) choice.getEventValues("createSession");
			switch (event) {
			case 0:
				switch (param) {      
				case 0: return self();			    
                default: return null;
                }
			default: return null;
			}
		}
		case 1: {
			ecno.bankingsystem.events.Withdraw w = 
			    (ecno.bankingsystem.events.Withdraw) choice.getEventValues("withdraw");
			switch (event) {
			case 0:
				switch (param) {    
                default: return null;
                }
			default: return null;
			}
		}
		case 2: {
			ecno.bankingsystem.events.CancelWithdraw c = 
			    (ecno.bankingsystem.events.CancelWithdraw) choice.getEventValues("cancelWithdraw");
			switch (event) {
			case 0:
				switch (param) {    
                default: return null;
                }
			default: return null;
			}
		}
		case 3: {
			ecno.bankingsystem.events.Balance b = 
			    (ecno.bankingsystem.events.Balance) choice.getEventValues("balance");
			switch (event) {
			case 0:
				switch (param) {      
				case 0: return self().getBalance();			    
                default: return null;
                }
			default: return null;
			}
		}
		default: return null;
		}  
	}	

	@Override
	public boolean evaluateCondition(PetriNetChoice choice) {
		int transition = choice.getTransition();
		// Note that this attribute self will be deleted in future versions 
		// of the ECNO code generator for ECNO nets. Therefore, the method
		// self() should be used instead of the variable self in your 
		// ECNO Net Java code snippets.
		emf.bankingsystem.Account self = self();
		
		switch (transition) {
		case 0: {
			ecno.bankingsystem.events.CreateSession c = 
                (ecno.bankingsystem.events.CreateSession) choice.getEventValues("createSession");
			return true; 
		}
		case 1: {
			ecno.bankingsystem.events.Withdraw w = 
                (ecno.bankingsystem.events.Withdraw) choice.getEventValues("withdraw");
			return self().getBalance() >= w.amount && w.amount > 0; 
		}
		case 2: {
			ecno.bankingsystem.events.CancelWithdraw c = 
                (ecno.bankingsystem.events.CancelWithdraw) choice.getEventValues("cancelWithdraw");
			return true; 
		}
		case 3: {
			ecno.bankingsystem.events.Balance b = 
                (ecno.bankingsystem.events.Balance) choice.getEventValues("balance");
			return true; 
		}
		default: return false;
		}  
	}	
	
	@Override
	public void executeAction(PetriNetChoice choice) {
		int transition = choice.getTransition();
		ParentAction parent = new ParentAction(choice);
		// Note that this attribute self will be deleted in future versions 
		// of the ECNO code generator for ECNO nets. Therefore, the method
		// self() should be used instead of the variable self in your 
		// ECNO Net Java code snippets.
		emf.bankingsystem.Account self = self();
		
		switch (transition) {
		case 0: {
			ecno.bankingsystem.events.CreateSession c =
                (ecno.bankingsystem.events.CreateSession) choice.getEventValues("createSession");
/* DO NOTHING */
            fire(transition);
			return; 
		}
		case 1: {
			ecno.bankingsystem.events.Withdraw w =
                (ecno.bankingsystem.events.Withdraw) choice.getEventValues("withdraw");
{
self().setBalance(self().getBalance()-w.amount);
}
            fire(transition);
			return; 
		}
		case 2: {
			ecno.bankingsystem.events.CancelWithdraw c =
                (ecno.bankingsystem.events.CancelWithdraw) choice.getEventValues("cancelWithdraw");
{
self().setBalance(self().getBalance() + c.amount);
}
            fire(transition);
			return; 
		}
		case 3: {
			ecno.bankingsystem.events.Balance b =
                (ecno.bankingsystem.events.Balance) choice.getEventValues("balance");
/* DO NOTHING */
            fire(transition);
			return; 
		}
		default: return;
		}  
	}	
	
	@Override
	public String[] getTransitionEvents(int transition) {
			switch (transition) {
		case 0: 
			return new String[] { "createSession" };
		case 1: 
			return new String[] { "withdraw" };
		case 2: 
			return new String[] { "cancelWithdraw" };
		case 3: 
			return new String[] { "balance" };
		default: return null;
		}  
	}
		
}

