/**
 * This is an automatically generated class. It was generated by the
 * ECNO framework. This class defines an ECNO Instance which can
 * be started via the main method (Run As -> Java Application).
 */
package ecno.example;

import org.eclipse.emf.ecore.EObject;

import dk.dtu.imm.se.ecno.engine.ExecutionEngine;
import dk.dtu.imm.se.ecno.gui.ECNOGUI;

public class Setting {

    final private emf.bankingsystem.BankingsystemFactory factory1;

	public Setting() {
		factory1 = emf.bankingsystem.BankingsystemFactory.eINSTANCE;
	}

	EObject createInstance(ExecutionEngine engine) {
		// Create the objects
        emf.bankingsystem.Setting o1 = factory1.createSetting();
        emf.bankingsystem.NaturalPerson o2 = factory1.createNaturalPerson();
        emf.bankingsystem.PhysicalBankCard o3 = factory1.createPhysicalBankCard();
        emf.bankingsystem.NaturalPerson o4 = factory1.createNaturalPerson();
        emf.bankingsystem.PhysicalBankCard o5 = factory1.createPhysicalBankCard();
        emf.bankingsystem.PhysicalBankCard o6 = factory1.createPhysicalBankCard();
        emf.bankingsystem.HW o7 = factory1.createHW();
        emf.bankingsystem.BankNote o8 = factory1.createBankNote();
        emf.bankingsystem.BankNote o9 = factory1.createBankNote();
        emf.bankingsystem.BankNote o10 = factory1.createBankNote();
        emf.bankingsystem.BankNote o11 = factory1.createBankNote();
        emf.bankingsystem.ATMController o12 = factory1.createATMController();
        emf.bankingsystem.BankGateway o13 = factory1.createBankGateway();
        emf.bankingsystem.AccountMngr o14 = factory1.createAccountMngr();
        emf.bankingsystem.Customer o15 = factory1.createCustomer();
        emf.bankingsystem.Customer o16 = factory1.createCustomer();
        emf.bankingsystem.Account o17 = factory1.createAccount();
        emf.bankingsystem.BankCard o18 = factory1.createBankCard();
        emf.bankingsystem.Account o19 = factory1.createAccount();
        emf.bankingsystem.BankCard o20 = factory1.createBankCard();
        emf.bankingsystem.BankCard o21 = factory1.createBankCard();
        emf.bankingsystem.Session o22 = factory1.createSession();	

		// Set the (simple) attributes
        o2.setName("Ekkart");
        o2.setUid(1);
        o3.setPin(0);
        o3.setNumber(1);
        o3.setUid(2);
        o4.setName("Lom");
        o4.setUid(3);
        o5.setPin(0);
        o5.setNumber(2);
        o5.setUid(4);
        o6.setPin(0);
        o6.setNumber(3);
        o6.setUid(5);
        o7.setUid(6);
        o8.setUid(7);
        o9.setUid(8);
        o10.setUid(9);
        o11.setUid(10);
        o12.setUid(11);
        o13.setUid(12);
        o14.setUid(14);
        o15.setName("Ekkart Kindler");
        o15.setId(2);
        o15.setUid(15);
        o16.setName("Lom Hillah");
        o16.setId(0);
        o16.setUid(16);
        o17.setBalance(2);
        o17.setUid(17);
        o18.setNumer(1);
        o18.setUid(18);
        o19.setBalance(4);
        o19.setUid(19);
        o20.setNumer(2);
        o20.setUid(20);
        o21.setNumer(3);
        o21.setUid(21);
        o22.setUid(22);	
   
		// Create the single references
        o3.setOwner(o2);
        o5.setOwner(o4);
        o6.setOwner(o4);
        o7.setController(o12);
        o12.setGateway(o13);
        o14.setGateway(o13);
        o15.setNatural(o2);
        o16.setNatural(o4);
        o18.setPhysical(o3);
        o18.setOwner(o15);
        o18.setAccount(o17);
        o20.setPhysical(o5);
        o20.setOwner(o16);
        o20.setAccount(o19);
        o21.setPhysical(o6);
        o21.setOwner(o16);
        o21.setAccount(o19);	

		// Create the multi references
        o1.getObjects().add(o2);
        o1.getObjects().add(o4);
        o1.getObjects().add(o7);
        o1.getObjects().add(o12);
        o1.getObjects().add(o13);
        o1.getObjects().add(o14);
        o4.getUses().add(o7);
        o7.getNotes().add(o8);
        o7.getNotes().add(o9);
        o7.getNotes().add(o10);
        o7.getNotes().add(o11);
        o14.getAccounts().add(o17);
        o14.getAccounts().add(o19);
        o14.getCustomers().add(o15);
        o14.getCustomers().add(o16);
        o14.getIdleSessions().add(o22);
        o15.getAccounts().add(o17);
        o16.getAccounts().add(o19);	
   		
		// Register the GUI objects with the controllers (objects 
		// not visible at a GUI will be added to the engine on the fly)
        engine.addElement(o2);
        engine.addElement(o3);
        engine.addElement(o4);
        engine.addElement(o5);
        engine.addElement(o6);
        engine.addElement(o22);
		return o1;
	}

    public static void main(String[] args) {
    	ExecutionEngine engine = ExecutionEngine.createNewInstance();
    	engine.addPackageAdapter(ecno.bankingsystem.model.BankingSystemECNOModel.getModel(engine));
    	if (!engine.resolveNamespaceImports()) {
    		System.err.println("Package imports could not be resolved");
    	}
    	new ECNOGUI(engine);
    	Setting instance = new Setting();
    	instance.createInstance(engine);
    }

}
