/**
 * This is an automatically generated class. It was generated by the
 * Petri net component of the ECNO framework. This class defines
 * the behaviour of an element, as defined by the Petri net.
 */
package example.ecno.vendingmachine.brewer.automata;

import org.eclipse.emf.ecore.EObject;

import dk.dtu.imm.se.ecno.model.runtime.ecnonets.AbstractPetrinetBehaviour;
import dk.dtu.imm.se.ecno.model.runtime.ecnonets.PetriNetChoice;
import dk.dtu.imm.se.ecno.runtime.ParentAction;
import dk.dtu.imm.se.ecno.core.IElementType;
import dk.dtu.imm.se.ecno.core.IPackageAdapter;
import dk.dtu.imm.se.ecno.engine.ExecutionEngine; 

@SuppressWarnings("unused")
public class TeaBrewer extends AbstractPetrinetBehaviour<example.emf.vendingmachinebrewers.TeaBrewer> {
	
	public TeaBrewer(ExecutionEngine engine, IElementType type,  EObject element) {
		super(engine, (example.emf.vendingmachinebrewers.TeaBrewer) element, new int[]{1, 0, 0}, new String[]{"t7", "t8", "t17", "t6"}, type );
	}
	
	@Override
	public boolean enabled(int t) {
		switch (t) {
		case 0:
			return marking.get(0) >= 1;
                    
		case 1:
			return marking.get(2) >= 1;
                    
		case 2:
			return true;
                    
		case 3:
			return marking.get(1) >= 1;
                    
		default:
			return false;	
		}
	}
	
	@Override
	public void consumeTokens(int t, int[] m) {
		switch (t) {
		case 0:
            m[0]--;
            break;
                    
		case 1:
            m[2]--;
            break;
                    
		case 2:
            break;
                    
		case 3:
            m[1]--;
            break;
                    
		}
	}

	@Override
	public boolean dropParentChoice(int t) {
		switch (t) {
		case 0:
			return false;                    
		case 1:
			return false;                    
		case 2:
			return false;                    
		case 3:
			return true;                    
		default:
			return false;	
		}
	}

	@Override
	public void fireImpl(int t) {
		if (! enabled(t))
			return;
		
		switch (t) {
		case 0:		
			marking.set(0, marking.get(0) - 1);
			marking.set(1,  marking.get(1) + 1);
			break;
			
		case 1:		
			marking.set(2, marking.get(2) - 1);
			marking.set(0,  marking.get(0) + 1);
			break;
			
		case 2:		
			break;
			
		case 3:		
			marking.set(1, marking.get(1) - 1);
			marking.set(2,  marking.get(2) + 1);
			break;
						
		}
	}
	
	@Override
	public String[] getTransitionEventParameterNames(int transition, int event) {
		switch (transition) {
		case 0:
			switch (event) {
			case 0:
				return new String[] { "name" };
            default: return new String[] {};
                }
		case 1:
			switch (event) {
			case 0:
				return new String[] {};
            default: return new String[] {};
                }
		case 2:
			switch (event) {
			case 0:
				return new String[] {};
            default: return new String[] {};
                }
		case 3:
			switch (event) {
			case 0:
				return new String[] {};
			case 1:
				return new String[] {};
            default: return new String[] {};
                }
		default: return new String[] {};
		}  
	}	
	
	@Override
	public Object getParamAssignment(PetriNetChoice choice, int event, int param) {
		int transition = choice.getTransition();
		// Note that this attribute self will be deleted in future versions 
		// of the ECNO code generator for ECNO nets. Therefore, the method
		// self() should be used instead of the variable self in your 
		// ECNO Net Java code snippets.
		example.emf.vendingmachinebrewers.TeaBrewer self = self();
				
		switch (transition) {
		case 0: {
			example.ecno.vendingmachine.brewer.events.Tea tea = 
			    (example.ecno.vendingmachine.brewer.events.Tea) choice.getEventValues("tea");
			switch (event) {
			case 0:
				switch (param) {      
				case 0: return "Test";			    
                default: return null;
                }
			default: return null;
			}
		}
		case 1: {
			switch (event) {
			case 0:
				switch (param) {    
                default: return null;
                }
			default: return null;
			}
		}
		case 2: {
			switch (event) {
			case 0:
				switch (param) {    
                default: return null;
                }
			default: return null;
			}
		}
		case 3: {
			switch (event) {
			case 0:
				switch (param) {    
                default: return null;
                }
			case 1:
				switch (param) {    
                default: return null;
                }
			default: return null;
			}
		}
		default: return null;
		}  
	}	

	@Override
	public boolean evaluateCondition(PetriNetChoice choice) {
		int transition = choice.getTransition();
		// Note that this attribute self will be deleted in future versions 
		// of the ECNO code generator for ECNO nets. Therefore, the method
		// self() should be used instead of the variable self in your 
		// ECNO Net Java code snippets.
		example.emf.vendingmachinebrewers.TeaBrewer self = self();
		
		switch (transition) {
		case 0: {
			example.ecno.vendingmachine.brewer.events.Tea tea = 
                (example.ecno.vendingmachine.brewer.events.Tea) choice.getEventValues("tea");
			return true; 
		}
		case 1: {
			return true; 
		}
		case 2: {
			return true; 
		}
		case 3: {
			return true; 
		}
		default: return false;
		}  
	}	
	
	@Override
	public void executeAction(PetriNetChoice choice) {
		int transition = choice.getTransition();
		ParentAction parent = new ParentAction(choice);
		// Note that this attribute self will be deleted in future versions 
		// of the ECNO code generator for ECNO nets. Therefore, the method
		// self() should be used instead of the variable self in your 
		// ECNO Net Java code snippets.
		example.emf.vendingmachinebrewers.TeaBrewer self = self();
		
		switch (transition) {
		case 0: {
			example.ecno.vendingmachine.brewer.events.Tea tea =
                (example.ecno.vendingmachine.brewer.events.Tea) choice.getEventValues("tea");
{
System.out.println(tea.name);
}
            fire(transition);
			return; 
		}
		case 1: {
/* DO NOTHING */
            fire(transition);
			return; 
		}
		case 2: {
/* DO NOTHING */
            fire(transition);
			return; 
		}
		case 3: {
{
  System.out.println("OUCH!");
}

            fire(transition);
			return; 
		}
		default: return;
		}  
	}	
	
	@Override
	public String[] getTransitionEvents(int transition) {
			switch (transition) {
		case 0: 
			return new String[] { "tea" };
		case 1: 
			return new String[] { "cup_in" };
		case 2: 
			return new String[] { "reset" };
		case 3: 
			return new String[] { "kick", "reset" };
		default: return null;
		}  
	}
		
}

