/**
 * This is an automatically generated class. It was generated by the
 * Petri net component of the ECNO framework. This class defines
 * the behaviour of a element, as defined by the Petri net.
 */
package example.ecno.vendingmachine.brewer.automata;

import dk.dtu.imm.se.ecno.engine.ExecutionEngine;

import example.emf.vendingmachinebrewers.VendingmachinebrewersPackage;
import dk.dtu.imm.se.ecno.model.adapter.EMFBehaviourAdaptor;
import dk.dtu.imm.se.ecno.model.runtime.SimpleEMFBehaviour;

public class VendingMachineBrewerBehaviour extends EMFBehaviourAdaptor {

	public VendingMachineBrewerBehaviour(ExecutionEngine engine) {
		super(engine);		
		this.addElementBehaviour(VendingmachinebrewersPackage.eINSTANCE.getTeaBrewer(), TeaBrewer.class);		
		this.addElementBehaviour(VendingmachinebrewersPackage.eINSTANCE.getCoffeeBrewer(), CoffeeBrewer.class);		
		
		this.addPackage(VendingmachinebrewersPackage.eINSTANCE, SimpleEMFBehaviour.class);
	}

}