/**
 * This is an automatically generated class. It was generated by the
 * ECNO framework. This class defines ECNOPackageAdapterFactory and which 
 * provides access to the package adapter of the model for the ECNO EMF engine.
 */
package ecno.bankingsystem.model;

import dk.dtu.imm.se.ecno.eclipse.adapterfactory.IPackageAdapterFactory;
import dk.dtu.imm.se.ecno.engine.ExecutionEngine;

public class BankingSystemPackageAdapterFactory implements IPackageAdapterFactory {

	public BankingSystemECNOModel getModel(ExecutionEngine engine) {
		return BankingSystemECNOModel.getModel(engine);
	}

	public String getECNOPackageURI() {
		return "http://bankingsystem";
	}

}
