/**
 * This is an automatically generated class. It was generated by the
 * ECNO framework. This class defines an ECNO Instance which can
 * be started via the main method (Run As -> Java Application).
 */
package example.ecno.vendingmachine.instance;

import dk.dtu.imm.se.ecno.engine.ExecutionEngine;
import dk.dtu.imm.se.ecno.gui.ECNOGUI;

public class VendingMachineInstanceManual {

	// TODO hange generator for this iteration
    final private example.emf.vendingmachine.VendingmachineFactory factory;
    final private example.emf.vendingmachineoutput.VendingmachineoutputFactory factory2;
    final private example.emf.vendingmachinebrewers.VendingmachinebrewersFactory factory3;

	public VendingMachineInstanceManual() {
		// TODO change generator for this iteration
		factory = example.emf.vendingmachine.VendingmachineFactory.eINSTANCE;
		factory2 = example.emf.vendingmachineoutput.VendingmachineoutputFactory.eINSTANCE;
		factory3 = example.emf.vendingmachinebrewers.VendingmachinebrewersFactory.eINSTANCE;
	}

	private void createInstance(ExecutionEngine engine) {
		// Create the objects
		// TODO adjust generator to using the right factory
        example.emf.vendingmachine.Slot o1 = factory.createSlot();
        example.emf.vendingmachine.Safe o2 = factory.createSafe();
        example.emf.vendingmachine.Panel o3 = factory.createPanel();
        example.emf.vendingmachine.Control o4 = factory.createControl();
        example.emf.vendingmachinebrewers.TeaBrewer o5 = factory3.createTeaBrewer();
        example.emf.vendingmachinebrewers.CoffeeBrewer o6 = factory3.createCoffeeBrewer();
        example.emf.vendingmachinebrewers.CoffeeBrewer o7 = factory3.createCoffeeBrewer();
        example.emf.vendingmachineoutput.Output o8 = factory2.createOutput();
        example.emf.vendingmachine.Coin o9 = factory.createCoin();
        example.emf.vendingmachine.Coin o10 = factory.createCoin();
        example.emf.vendingmachine.Coin o11 = factory.createCoin();	

		// Set the (simple) attributes	
   
		// Create the single references
        o1.setSafe(o2);
        o5.setControl(o4);
        o6.setControl(o4);
        o7.setControl(o4);	

		// Create the multi references
        o3.getControl().add(o4);
        o4.getSlot().add(o1);
        o8.getBrewer().add(o5);
        o8.getBrewer().add(o6);
        o8.getBrewer().add(o7);
        o9.getSlot().add(o1);
        o10.getSlot().add(o1);
        o11.getSlot().add(o1);	
   		
		// Register the GUI objects with the controllers (objects 
		// not visible at a GUI will be added to the engine on the fly)
        engine.addElement(o3);
        engine.addElement(o8);
        engine.addElement(o9);
        engine.addElement(o10);
        engine.addElement(o11);
	}

    public static void main(String[] args) {
    	ExecutionEngine engine = ExecutionEngine.createNewInstance();
    	// TODO change generator for this iteration
    	engine.addPackageAdapter(example.ecno.vendingmachine.coordination.VendingMachineModel.getModel(engine));
    	engine.addPackageAdapter(example.ecno.vendingmachine.output.coordination.VendingMachineOutputModel.getModel(engine));
    	engine.addPackageAdapter(example.ecno.vendingmachine.brewer.coordination.VendingMachineModel.getModel(engine));
    	if (!engine.resolveNamespaceImports()) {
    		// TODO change generator for this error message
    		System.err.println("Package imports could not be resolved");
    	}
    	new ECNOGUI(engine);        	
    	VendingMachineInstanceManual instance = new VendingMachineInstanceManual();
    	instance.createInstance(engine);
    }

}
