<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="vendingmachinebrewers"
    nsURI="http://se.imm.dtu.dk/vendingmachine/brewers/1.0" nsPrefix="vendingmachinebrewers">
  <eClassifiers xsi:type="ecore:EClass" name="CoffeeBrewer" eSuperTypes="../../dk.dtu.imm.se.ecno.examples.vendingmachine.split.part1/models/VendingMachine.ecore#//Brewer"/>
  <eClassifiers xsi:type="ecore:EClass" name="TeaBrewer" eSuperTypes="../../dk.dtu.imm.se.ecno.examples.vendingmachine.split.part1/models/VendingMachine.ecore#//Brewer"/>
</ecore:EPackage>
