<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ecnogen"
    nsURI="http://ecno.se.imm.dtu.dk/ecno/gen" nsPrefix="ecnogen">
  <eClassifiers xsi:type="ecore:EClass" name="ECNOGenModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="emfGenModel" upperBound="-1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.codegen.ecore/model/GenModel.ecore#//GenModel"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ecnoModel" eType="ecore:EClass ecno.ecore#//Package"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="basePathECNOEvents" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="basePathECNOAutomata" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AutomataFactoryClassName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="BehaviourModel" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="basePathModelClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ModelClassName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PackageAdapterFactoryClassName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="required" upperBound="-1"
        eType="#//ECNOGenModel"/>
  </eClassifiers>
</ecore:EPackage>
