/**
 * This is an automatically generated class. It was generated by the
 * Petri net component of the ECNO framework. This class defines
 * the behaviour of a element, as defined by the Petri net.
 */
package dk.dtu.imm.se.ecno.example.workers.automata;

import dk.dtu.imm.se.ecno.engine.ExecutionEngine;

import dk.dtu.imm.se.emf.example.workers.WorkersPackage;
import dk.dtu.imm.se.ecno.model.adapter.EMFBehaviourAdaptor;
import dk.dtu.imm.se.ecno.model.runtime.SimpleEMFBehaviour;

public class WorkersAutomata extends EMFBehaviourAdaptor {

	public WorkersAutomata(ExecutionEngine engine) {
		super(engine);		
		this.addElementBehaviour(WorkersPackage.eINSTANCE.getWorker(), Worker.class);		
		this.addElementBehaviour(WorkersPackage.eINSTANCE.getJob(), Job.class);		
		this.addElementBehaviour(WorkersPackage.eINSTANCE.getCar(), Car.class);		
		
		this.addPackage(WorkersPackage.eINSTANCE, SimpleEMFBehaviour.class);
	}

}