/**
 * This is an automatically generated class. It was generated by the
 * ECNO framework. This class defines ECNOPackageAdapterFactory and which 
 * provides access to the package adapter of the model for the ECNO EMF engine.
 */
package dk.dtu.imm.se.ecno.examples.workers.coordination;

import dk.dtu.imm.se.ecno.eclipse.adapterfactory.IPackageAdapterFactory;
import dk.dtu.imm.se.ecno.engine.ExecutionEngine;

public class WorkersModelFactory implements IPackageAdapterFactory {

	public WorkersModel getModel(ExecutionEngine engine) {
		return WorkersModel.getModel(engine);
	}

	public String getECNOPackageURI() {
		return "dk.dtu.imm.se.ecno.example.workers.collective";
	}

}
