/**
 * This is an automatically generated class. It was generated by the
 * ECNO framework. This class defines ECNOPackageAdapterFactory and which 
 * provides access to the package adapter of the model for the ECNO EMF engine.
 */
package dk.dtu.compute.se.ecno.processalgebras.globalbehaviour;

import dk.dtu.imm.se.ecno.eclipse.adapterfactory.IPackageAdapterFactory;
import dk.dtu.imm.se.ecno.engine.ExecutionEngine;

public class ProcessAlgebraPackageAdapterFactory implements IPackageAdapterFactory {

	public ProcessAlgebraCoordinationModel getModel(ExecutionEngine engine) {
		return ProcessAlgebraCoordinationModel.getModel(engine);
	}

	public String getECNOPackageURI() {
		return "http://se.compute.dtu.dk/processalgebras/ecno";
	}

}
