/**
 * This is an automatically generated class. It was generated by the
 * Petri net component of the ECNO framework. This class defines
 * the behaviour of a element, as defined by the Petri net.
 */
package dk.dtu.imm.se.ecno.pn.example.vendingmachine.behaviours;

import dk.dtu.imm.se.ecno.runtime.ParentAction;
import dk.dtu.imm.se.ecno.engine.ExecutionEngine;

import dk.dtu.imm.se.ecno.pn.model.ElementType;
import dk.dtu.imm.se.ecno.pn.runtime.AbstractPetrinetBehaviour;
import dk.dtu.imm.se.ecno.pn.runtime.Element;
import dk.dtu.imm.se.ecno.pn.runtime.PetriNetChoice;

import dk.dtu.imm.se.ecno.pn.model.Reference;
import dk.dtu.imm.se.ecno.pn.example.vendingmachine.VendingMachineModel;

public class Coin extends AbstractPetrinetBehaviour {

final Reference coin_slot_ref = VendingMachineModel.getVendingMachineModel().getReference_coin_slot(); 

	public Coin(ExecutionEngine engine, ElementType type, Element self) {
		super(engine, new int[]{1, 0, 0}, new String[]{"t3", "t11", "t12"}, type, self);
	}

	@Override
	public boolean enabled(int t) {
		switch (t) {
		case 0:
			return marking[0] >= 1;
                    
		case 1:
			return marking[1] >= 1;
                    
		case 2:
			return marking[1] >= 1;
                    
		default:
			return false;	
		}
	}

	@Override
	public boolean dropParentChoice(int t) {
		switch (t) {
		case 0:
			return false;                    
		case 1:
			return false;                    
		case 2:
			return false;                    
		default:
			return false;	
		}
	}

	@Override
	public void fireImpl(int t) {
		if (! enabled(t))
			return;
		
		switch (t) {
		case 0:		
			marking[0] =  marking[0] - 1;
			marking[1] =  marking[1] + 1;
			break;
			
		case 1:		
			marking[1] =  marking[1] - 1;
			marking[0] =  marking[0] + 1;
			break;
			
		case 2:		
			marking[1] =  marking[1] - 1;
			marking[2] =  marking[2] + 1;
			break;
						
		}
	}
	
	@Override
	public boolean doesAssignParam(int transition, int event, int param) {
		switch (transition) {
		case 0:
			switch (event) {
			case 0:
				switch (param) {
				case 0: return true;			
				case 1: return false;			    
                default: return false;
                }
			default: return false;
			}
		case 1:
			switch (event) {
			case 0:
				switch (param) {
				case 0: return false;			    
                default: return false;
                }
			default: return false;
			}
		case 2:
			switch (event) {
			case 0:
				switch (param) {
				case 0: return true;			
				case 1: return false;			    
                default: return false;
                }
			default: return false;
			}
		default: return false;
		}  
	}	
	
	@Override
	public Object getParamAssignment(PetriNetChoice choice, int event, int param) {
		int transition = choice.getTransition();
		{
			dk.dtu.imm.se.ecno.pn.example.vendingmachine.Coin self = (dk.dtu.imm.se.ecno.pn.example.vendingmachine.Coin) getElement();		
			switch (transition) {
			case 0: {
				Eventinsert_Values i = (Eventinsert_Values) choice.getEventValues("insert");
				switch (event) {
				case 0:
					switch (param) {      
					case 0: return self;			    
                	default: return null;
                	}
				default: return null;
				}
			}
			case 1: {
				Eventreturn__Values r = (Eventreturn__Values) choice.getEventValues("return_");
				switch (event) {
				case 0:
					switch (param) {    
                	default: return null;
                	}
				default: return null;
				}
			}
			case 2: {
				Eventpass_Values p = (Eventpass_Values) choice.getEventValues("pass");
				switch (event) {
				case 0:
					switch (param) {      
					case 0: return self;			    
                	default: return null;
                	}
				default: return null;
				}
			}
			default: return null;
			}
		}
	}

	@Override
	public boolean evaluateCondition(PetriNetChoice choice) {
		int transition = choice.getTransition();
		{
			dk.dtu.imm.se.ecno.pn.example.vendingmachine.Coin self = (dk.dtu.imm.se.ecno.pn.example.vendingmachine.Coin) getElement();
			switch (transition) {
			case 0: {
				Eventinsert_Values i = (Eventinsert_Values) choice.getEventValues("insert");
				return true; 
			}
			case 1: {
				Eventreturn__Values r = (Eventreturn__Values) choice.getEventValues("return_");
				return true; 
			}
			case 2: {
				Eventpass_Values p = (Eventpass_Values) choice.getEventValues("pass");
				return true; 
			}
			default: return false;
			}
		}
	}	
	
	@Override
	public void executeAction(PetriNetChoice choice) {
		int transition = choice.getTransition();
		{
			dk.dtu.imm.se.ecno.pn.example.vendingmachine.Coin self = (dk.dtu.imm.se.ecno.pn.example.vendingmachine.Coin) getElement();		
			ParentAction parent = new ParentAction(choice);
			switch (transition) {
			case 0: {
				Eventinsert_Values i = (Eventinsert_Values) choice.getEventValues("insert");
{
  self.removeLink(coin_slot_ref,i.slot);
  engine.removeElement(self);
}

            	fire(transition);
				return; 
			}
			case 1: {
				Eventreturn__Values r = (Eventreturn__Values) choice.getEventValues("return_");
{
  self.addLink(coin_slot_ref,r.slot);
  engine.addElement(self);
}

            	fire(transition);
				return; 
			}
			case 2: {
				Eventpass_Values p = (Eventpass_Values) choice.getEventValues("pass");
/* DO NOTHING */
            	fire(transition);
				return; 
			}
			default: return;
			}
		}
	}	
	
	@Override
	public String[] getTransitionEvents(int transition) {
			switch (transition) {
		case 0: 
			return new String[] { "insert" };
		case 1: 
			return new String[] { "return_" };
		case 2: 
			return new String[] { "pass" };
		default: return null;
		}  
	}
		
}

