/**
 * This is an automatically generated class. It was generated by the
 * Petri net component of the ECNO framework. This class defines
 * the behaviour of a element, as defined by the Petri net.
 */
package dk.dtu.imm.se.ecno.pn.example.vendingmachine.behaviours;

import dk.dtu.imm.se.ecno.runtime.ParentAction;
import dk.dtu.imm.se.ecno.engine.ExecutionEngine;

import dk.dtu.imm.se.ecno.pn.model.ElementType;
import dk.dtu.imm.se.ecno.pn.runtime.AbstractPetrinetBehaviour;
import dk.dtu.imm.se.ecno.pn.runtime.Element;
import dk.dtu.imm.se.ecno.pn.runtime.PetriNetChoice;

public class Control extends AbstractPetrinetBehaviour {
 

	public Control(ExecutionEngine engine, ElementType type, Element self) {
		super(engine, new int[]{}, new String[]{"t4", "t5", "t6"}, type, self);
	}

	@Override
	public boolean enabled(int t) {
		switch (t) {
		case 0:
			return true;
                    
		case 1:
			return true;
                    
		case 2:
			return true;
                    
		default:
			return false;	
		}
	}

	@Override
	public boolean dropParentChoice(int t) {
		switch (t) {
		case 0:
			return false;                    
		case 1:
			return false;                    
		case 2:
			return false;                    
		default:
			return false;	
		}
	}

	@Override
	public void fireImpl(int t) {
		if (! enabled(t))
			return;
		
		switch (t) {
		case 0:		
			break;
			
		case 1:		
			break;
			
		case 2:		
			break;
						
		}
	}
	
	@Override
	public boolean doesAssignParam(int transition, int event, int param) {
		switch (transition) {
		case 0:
			switch (event) {
			case 0:
				switch (param) {    
                default: return false;
                }
			case 1:
				switch (param) {    
                default: return false;
                }
			default: return false;
			}
		case 1:
			switch (event) {
			case 0:
				switch (param) {
				case 0: return false;			
				case 1: return false;			    
                default: return false;
                }
			case 1:
				switch (param) {    
                default: return false;
                }
			default: return false;
			}
		case 2:
			switch (event) {
			case 0:
				switch (param) {
				case 0: return false;			
				case 1: return false;			    
                default: return false;
                }
			case 1:
				switch (param) {    
                default: return false;
                }
			default: return false;
			}
		default: return false;
		}  
	}	
	
	@Override
	public Object getParamAssignment(PetriNetChoice choice, int event, int param) {
		int transition = choice.getTransition();
		{
			dk.dtu.imm.se.ecno.pn.example.vendingmachine.Control self = (dk.dtu.imm.se.ecno.pn.example.vendingmachine.Control) getElement();		
			switch (transition) {
			case 0: {
				switch (event) {
				case 0:
					switch (param) {    
                	default: return null;
                	}
				case 1:
					switch (param) {    
                	default: return null;
                	}
				default: return null;
				}
			}
			case 1: {
				Eventpass_Values p = (Eventpass_Values) choice.getEventValues("pass");
				switch (event) {
				case 0:
					switch (param) {    
                	default: return null;
                	}
				case 1:
					switch (param) {    
                	default: return null;
                	}
				default: return null;
				}
			}
			case 2: {
				Eventpass_Values p = (Eventpass_Values) choice.getEventValues("pass");
				switch (event) {
				case 0:
					switch (param) {    
                	default: return null;
                	}
				case 1:
					switch (param) {    
                	default: return null;
                	}
				default: return null;
				}
			}
			default: return null;
			}
		}
	}

	@Override
	public boolean evaluateCondition(PetriNetChoice choice) {
		int transition = choice.getTransition();
		{
			dk.dtu.imm.se.ecno.pn.example.vendingmachine.Control self = (dk.dtu.imm.se.ecno.pn.example.vendingmachine.Control) getElement();
			switch (transition) {
			case 0: {
				return true; 
			}
			case 1: {
				Eventpass_Values p = (Eventpass_Values) choice.getEventValues("pass");
				return true; 
			}
			case 2: {
				Eventpass_Values p = (Eventpass_Values) choice.getEventValues("pass");
				return true; 
			}
			default: return false;
			}
		}
	}	
	
	@Override
	public void executeAction(PetriNetChoice choice) {
		int transition = choice.getTransition();
		{
			dk.dtu.imm.se.ecno.pn.example.vendingmachine.Control self = (dk.dtu.imm.se.ecno.pn.example.vendingmachine.Control) getElement();		
			ParentAction parent = new ParentAction(choice);
			switch (transition) {
			case 0: {
/* DO NOTHING */
            	fire(transition);
				return; 
			}
			case 1: {
				Eventpass_Values p = (Eventpass_Values) choice.getEventValues("pass");
/* DO NOTHING */
            	fire(transition);
				return; 
			}
			case 2: {
				Eventpass_Values p = (Eventpass_Values) choice.getEventValues("pass");
/* DO NOTHING */
            	fire(transition);
				return; 
			}
			default: return;
			}
		}
	}	
	
	@Override
	public String[] getTransitionEvents(int transition) {
			switch (transition) {
		case 0: 
			return new String[] { "cancel", "reset" };
		case 1: 
			return new String[] { "pass", "coffee" };
		case 2: 
			return new String[] { "pass", "tea" };
		default: return null;
		}  
	}
		
}

