/**
 * This is an automatically generated class. It was generated by the
 * Petri net component of the ECNO framework. This class defines
 * the behaviour of a element, as defined by the Petri net.
 */
package example.ecno.vendingmachine.output.automata;

import dk.dtu.imm.se.ecno.engine.ExecutionEngine;

import example.emf.vendingmachineoutput.VendingmachineoutputPackage;
import dk.dtu.imm.se.ecno.model.adapter.EMFBehaviourAdaptor;
import dk.dtu.imm.se.ecno.model.runtime.SimpleEMFBehaviour;

public class VendingMachineOutputBehaviour extends EMFBehaviourAdaptor {

	public VendingMachineOutputBehaviour(ExecutionEngine engine) {
		super(engine);		
		this.addElementBehaviour(VendingmachineoutputPackage.eINSTANCE.getOutput(), Output.class);		
		
		this.addPackage(VendingmachineoutputPackage.eINSTANCE, SimpleEMFBehaviour.class);
	}

}