/**
 * This is an automatically generated class. It was generated by the
 * Petri net component of the ECNO framework. This class defines
 * the behaviour of an element, as defined by the Petri net.
 */
package dk.dtu.compute.se.ecno.processalgebras.localbehaviour;

import org.eclipse.emf.ecore.EObject;

import dk.dtu.imm.se.ecno.model.runtime.ecnonets.AbstractPetrinetBehaviour;
import dk.dtu.imm.se.ecno.model.runtime.ecnonets.PetriNetChoice;
import dk.dtu.imm.se.ecno.runtime.ParentAction;
import dk.dtu.imm.se.ecno.core.IElementType;
import dk.dtu.imm.se.ecno.core.IPackageAdapter;
import dk.dtu.imm.se.ecno.engine.ExecutionEngine; 

@SuppressWarnings("unused")
public class ActionInst extends AbstractPetrinetBehaviour<dk.dtu.compute.se.emf.processalgebra.ActionInst> {
	
	public ActionInst(ExecutionEngine engine, IElementType type,  EObject element) {
		super(engine, (dk.dtu.compute.se.emf.processalgebra.ActionInst) element, new int[]{1, 0, 0}, new String[]{"t0", "t1", "t2", "t3"}, type );
	}
	
	@Override
	public boolean enabled(int t) {
		switch (t) {
		case 0:
			return marking.get(0) >= 1;
                    
		case 1:
			return marking.get(0) >= 1;
                    
		case 2:
			return marking.get(1) >= 1;
                    
		case 3:
			return marking.get(2) >= 1;
                    
		default:
			return false;	
		}
	}
	
	@Override
	public void consumeTokens(int t, int[] m) {
		switch (t) {
		case 0:
            m[0]--;
            break;
                    
		case 1:
            m[0]--;
            break;
                    
		case 2:
            m[1]--;
            break;
                    
		case 3:
            m[2]--;
            break;
                    
		}
	}

	@Override
	public boolean dropParentChoice(int t) {
		switch (t) {
		case 0:
			return false;                    
		case 1:
			return false;                    
		case 2:
			return false;                    
		case 3:
			return false;                    
		default:
			return false;	
		}
	}

	@Override
	public void fireImpl(int t) {
		if (! enabled(t))
			return;
		
		switch (t) {
		case 0:		
			marking.set(0, marking.get(0) - 1);
			marking.set(1,  marking.get(1) + 1);
			break;
			
		case 1:		
			marking.set(0, marking.get(0) - 1);
			marking.set(2,  marking.get(2) + 1);
			break;
			
		case 2:		
			marking.set(1, marking.get(1) - 1);
			marking.set(1,  marking.get(1) + 1);
			break;
			
		case 3:		
			marking.set(2, marking.get(2) - 1);
			marking.set(2,  marking.get(2) + 1);
			break;
						
		}
	}
	
	@Override
	public String[] getTransitionEventParameterNames(int transition, int event) {
		switch (transition) {
		case 0:
			switch (event) {
			case 0:
				return new String[] { "pos", "terminating" };
            default: return new String[] {};
                }
		case 1:
			switch (event) {
			case 0:
				return new String[] { "neg", "terminating" };
            default: return new String[] {};
                }
		case 2:
			switch (event) {
			case 0:
				return new String[] { "pos", "terminating" };
            default: return new String[] {};
                }
		case 3:
			switch (event) {
			case 0:
				return new String[] { "neg", "terminating" };
            default: return new String[] {};
                }
		default: return new String[] {};
		}  
	}	
	
	@Override
	public Object getParamAssignment(PetriNetChoice choice, int event, int param) {
		int transition = choice.getTransition();
		// Note that this attribute self will be deleted in future versions 
		// of the ECNO code generator for ECNO nets. Therefore, the method
		// self() should be used instead of the variable self in your 
		// ECNO Net Java code snippets.
		dk.dtu.compute.se.emf.processalgebra.ActionInst self = self();
				
		switch (transition) {
		case 0: {
			dk.dtu.compute.se.ecno.processalgebras.events.Action a = 
			    (dk.dtu.compute.se.ecno.processalgebras.events.Action) choice.getEventValues("action");
			switch (event) {
			case 0:
				switch (param) {      
				case 0: return self();			      
				case 1: return self();			    
                default: return null;
                }
			default: return null;
			}
		}
		case 1: {
			dk.dtu.compute.se.ecno.processalgebras.events.Action a = 
			    (dk.dtu.compute.se.ecno.processalgebras.events.Action) choice.getEventValues("action");
			switch (event) {
			case 0:
				switch (param) {      
				case 0: return self();			      
				case 1: return self();			    
                default: return null;
                }
			default: return null;
			}
		}
		case 2: {
			dk.dtu.compute.se.ecno.processalgebras.events.Action a = 
			    (dk.dtu.compute.se.ecno.processalgebras.events.Action) choice.getEventValues("action");
			switch (event) {
			case 0:
				switch (param) {      
				case 0: return self();			      
				case 1: return self();			    
                default: return null;
                }
			default: return null;
			}
		}
		case 3: {
			dk.dtu.compute.se.ecno.processalgebras.events.Action a = 
			    (dk.dtu.compute.se.ecno.processalgebras.events.Action) choice.getEventValues("action");
			switch (event) {
			case 0:
				switch (param) {      
				case 0: return self();			      
				case 1: return self();			    
                default: return null;
                }
			default: return null;
			}
		}
		default: return null;
		}  
	}	

	@Override
	public boolean evaluateCondition(PetriNetChoice choice) {
		int transition = choice.getTransition();
		// Note that this attribute self will be deleted in future versions 
		// of the ECNO code generator for ECNO nets. Therefore, the method
		// self() should be used instead of the variable self in your 
		// ECNO Net Java code snippets.
		dk.dtu.compute.se.emf.processalgebra.ActionInst self = self();
		
		switch (transition) {
		case 0: {
			dk.dtu.compute.se.ecno.processalgebras.events.Action a = 
                (dk.dtu.compute.se.ecno.processalgebras.events.Action) choice.getEventValues("action");
			return !self().getAction().isBar(); 
		}
		case 1: {
			dk.dtu.compute.se.ecno.processalgebras.events.Action a = 
                (dk.dtu.compute.se.ecno.processalgebras.events.Action) choice.getEventValues("action");
			return self().getAction().isBar(); 
		}
		case 2: {
			dk.dtu.compute.se.ecno.processalgebras.events.Action a = 
                (dk.dtu.compute.se.ecno.processalgebras.events.Action) choice.getEventValues("action");
			return true; 
		}
		case 3: {
			dk.dtu.compute.se.ecno.processalgebras.events.Action a = 
                (dk.dtu.compute.se.ecno.processalgebras.events.Action) choice.getEventValues("action");
			return true; 
		}
		default: return false;
		}  
	}	
	
	@Override
	public void executeAction(PetriNetChoice choice) {
		int transition = choice.getTransition();
		ParentAction parent = new ParentAction(choice);
		// Note that this attribute self will be deleted in future versions 
		// of the ECNO code generator for ECNO nets. Therefore, the method
		// self() should be used instead of the variable self in your 
		// ECNO Net Java code snippets.
		dk.dtu.compute.se.emf.processalgebra.ActionInst self = self();
		
		switch (transition) {
		case 0: {
			dk.dtu.compute.se.ecno.processalgebras.events.Action a =
                (dk.dtu.compute.se.ecno.processalgebras.events.Action) choice.getEventValues("action");
{
self().dispose();
}
            fire(transition);
			return; 
		}
		case 1: {
			dk.dtu.compute.se.ecno.processalgebras.events.Action a =
                (dk.dtu.compute.se.ecno.processalgebras.events.Action) choice.getEventValues("action");
{
self().dispose();
}
            fire(transition);
			return; 
		}
		case 2: {
			dk.dtu.compute.se.ecno.processalgebras.events.Action a =
                (dk.dtu.compute.se.ecno.processalgebras.events.Action) choice.getEventValues("action");
{
self().dispose();
}
            fire(transition);
			return; 
		}
		case 3: {
			dk.dtu.compute.se.ecno.processalgebras.events.Action a =
                (dk.dtu.compute.se.ecno.processalgebras.events.Action) choice.getEventValues("action");
{
self().dispose();
}
            fire(transition);
			return; 
		}
		default: return;
		}  
	}	
	
	@Override
	public String[] getTransitionEvents(int transition) {
			switch (transition) {
		case 0: 
			return new String[] { "action" };
		case 1: 
			return new String[] { "action" };
		case 2: 
			return new String[] { "action" };
		case 3: 
			return new String[] { "action" };
		default: return null;
		}  
	}
		
}

