/**
 * This is an automatically generated class. It was generated by the
 * ECNO framework. It defines an Event_Value class.
 */
package example.ecno.vendingmachine.events;

import java.util.List;

import dk.dtu.imm.se.ecno.core.IEventType;
import dk.dtu.imm.se.ecno.core.IFormalParameter;
import dk.dtu.imm.se.ecno.runtime.Event; 
import dk.dtu.imm.se.ecno.runtime.Event_Values;

public class Drink extends Event_Values  {

	final public example.emf.vendingmachine.Brewer brewer;

	public Drink(IEventType type, Event event) {
		super(type.getDirectSuperType(), event);
		List<IFormalParameter> formalParameters = type.getFormalParametersList();           	
	    brewer = (example.emf.vendingmachine.Brewer) event.getParameter(formalParameters.get(0)).getValue();
	}
}
