/**
 * This is an automatically generated class. It was generated by the
 * ECNO framework. It defines an EventExtension_Value class.
 */
package example.ecno.vendingmachine.events;

import java.util.List;

import dk.dtu.imm.se.ecno.core.IEventTypeExtension;
import dk.dtu.imm.se.ecno.core.IFormalParameter;
import dk.dtu.imm.se.ecno.runtime.Event;
import dk.dtu.imm.se.ecno.runtime.EventExtension_Values; 

public class Yyy extends EventExtension_Values {

	final public java.lang.String test;

	public Yyy(IEventTypeExtension typeExtension, Event event) {
		super(typeExtension, event);
		List<IFormalParameter> formalParameters = typeExtension.getFormalParametersList();           	
	    test = (java.lang.String) event.getParameter(formalParameters.get(0)).getValue();
	}
	
	public dk.dtu.imm.se.ecno.runtime.Event_Values base() {
		return (dk.dtu.imm.se.ecno.runtime.Event_Values) getBaseEvent_Values();
	}

}
